### ISSUE TITLE
Pagination and search bug

### ISSUE THREAD

**Issue by jt64fr** [luverolla/js-datatable#2]
Hi,   
i like your code but i made some changes to be able to use it.
I added a second array `dataOriginal` containing the original data, and I used your `data` array to filter and paginate.    
When the user changes his search I use the  array `dataOriginal` to populate `data`array.

Otherwise very good job ! easy to implement and to use.

**Comment by luverolla** [comment]
Hi.
With the last commit, the bug you referred to, should have been fixed, so I'm closing this issue. Feel free to reopen it or open a new one, if there are other problems.
Thank you for having reported the bug and for having appreciated my job.

**Comment by jt64fr** [comment]
Hi,
yes it's okay now, perfect  :)
